import "~/styles/globals.css";

import { type Metadata } from "next";
import { Fanwood_Text } from "next/font/google";

const fanwoodText = Fanwood_Text({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio - Jibin James",
  description: "Boilerplate Generated by create-t3-app, modified by Jibin",
  icons: [{ rel: "icon", url: "/" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${fanwoodText.className}`}>
      <body className="bg-body-bg-color flex justify-center">{children}</body>
    </html>
  );
}
